---
- hosts: all

  vars:
  - oah_command: remove

  vars_files:
    - ../oah-config.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    # Essential roles.
#     - oah.drupal
#     - oah.desktop
#     - oah.VSCode
      - oah.gh
      - oah.jupyter

    # Conditionally-installed roles.

    # Roles for security and stability on production.

  tasks:
