---
- hosts: all || localhost
  vars:
  - oah_command: install
  - HOME: /home/vagrant

  vars_files:
    - ../oah-config.yml

  pre_tasks:
    - name: "printing debug msg"
      become: yes
      debug:
        msg: In pre_tasks
    # Will need the shell provision to install python-minimal first
#     - name: Install python3 and python3-pip for Ansible
#       become: yes
#       raw: test -e /usr/bin/python || (sudo apt -y update && apt install -y python3.8 && sudo apt install -y python3-pip)
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
    
    - name: Checking for bes
      stat:
        path: "{{HOME}}/.besman"
      register: besman
      failed_when: not besman.stat.exists
    
    - name: Checking for oah
      stat:
        path: "{{HOME}}/.oah"
      register: oah
      failed_when: not oah.stat.exists
  roles:
    - oah.apache
    - oah.mysql
    - oah.php
    - oah.drupal
#     - oah.chrome

      #- oah.vscode


    # Conditionally-installed roles.

    # Roles for security and stability on production.
